import shutil
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlmodel import SQLModel

from activemodel.session_manager import get_engine
from sqlalchemy import inspect


def clear_directory(path: Path) -> None:
    """Remove all files and directories from a test scratch directory."""

    for child in path.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
            continue

        child.unlink()


def test_migrations():
    # all of the tables should be loaded into the SQLModel metadata before running alembic
    assert len(SQLModel.metadata.tables) >= 4

    # if we create the tables before running alembic, it won't be picked up
    inspector = inspect(get_engine())
    assert not inspector.get_table_names(), "Expected no tables in the DB."

    test_root = Path(__file__).parent
    migrations_path = test_root / "migrations"
    versions_path = migrations_path / "versions"

    # ensure the directory exists (it might be ignored by git)
    versions_path.mkdir(parents=True, exist_ok=True)

    # Alembic imports generated revisions, which can leave `__pycache__` directories behind.
    clear_directory(versions_path)

    # Configure Alembic
    alembic_cfg = Config(str(migrations_path / "alembic.ini"))
    alembic_cfg.set_main_option("script_location", str(test_root / "migrations"))

    # Generate a revision with autogenerate enabled
    command.revision(alembic_cfg, message="autogenerated migration", autogenerate=True)

    # Inspect the migration file if needed
    migration_files = sorted(
        path
        for path in versions_path.iterdir()
        if path.is_file() and path.suffix == ".py"
    )
    migration_path = migration_files[-1]

    migration_contents = migration_path.read_text()

    # ensure that the computed properties exist
    assert "op.create_table('example_with_id'" in migration_contents
    assert "op.f('example_with_id_example_record_id_fkey'))" in migration_contents
    assert "name=op.f('example_with_id_another_example_id_fkey'))" in migration_contents
