"""autogenerated migration

Revision ID: 515ec40209aa
Revises: 
Create Date: 2026-03-30 11:43:43.083104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import activemodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515ec40209aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('after_find_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('after_find_model_pkey'))
    )
    op.create_table('after_initialize_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('after_initialize_model_pkey'))
    )
    op.create_table('another_example',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=False, comment='TypeID with prefix: myotherid'),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('another_example_pkey'))
    )
    op.create_table('delete_example_with_id',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='delete_test'), nullable=False, comment='TypeID with prefix: delete_test'),
    sa.PrimaryKeyConstraint('id', name=op.f('delete_example_with_id_pkey'))
    )
    op.create_table('delete_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('delete_model_pkey'))
    )
    op.create_table('example_record',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='test_record'), nullable=False, comment='TypeID with prefix: test_record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('something', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('another_with_index', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('example_record_pkey'))
    )
    op.create_index(op.f('example_record_another_with_index_idx'), 'example_record', ['another_with_index'], unique=True)
    op.create_table('example_with_comments',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='ex_comments'), nullable=False, comment='TypeID with prefix: ex_comments'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('a_string_field_without_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='a doc string for a string field without a field'),
    sa.Column('a_string_field_with_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='a doc string for a string field with a field'),
    sa.Column('field_with_sa_column', sa.String(), nullable=True, comment='a doc string for a string field with a field and a sa_column'),
    sa.Column('field_with_sa_column_args', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='a doc string for a string field with a field and a sa_column_kwargs'),
    sa.Column('field_with_empty_sa_column_args', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='a doc string for a string field with a field and an empty sa_column_kwargs'),
    sa.PrimaryKeyConstraint('id', name=op.f('example_with_comments_pkey')),
    comment='Expected table comment'
    )
    op.create_table('example_with_jsonb',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='json_test'), nullable=False, comment='TypeID with prefix: json_test'),
    sa.Column('list_field', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_list_field', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generic_list_field', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('object_field', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unstructured_field', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semi_structured_field', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_object_field', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('old_optional_object_field', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tuple_field', test.nested_pydantic_json_test.CustomTupleType(), nullable=False),
    sa.Column('optional_tuple', test.nested_pydantic_json_test.CustomTupleType(), nullable=True),
    sa.Column('normal_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('example_with_jsonb_pkey'))
    )
    op.create_table('example_with_simple_json',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='simple_json_test'), nullable=False, comment='TypeID with prefix: simple_json_test'),
    sa.Column('object_field', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('example_with_simple_json_pkey'))
    )
    op.create_table('example_without_comments',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='ex_wo_comments'), nullable=False, comment='TypeID with prefix: ex_wo_comments'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('example_without_comments_pkey'))
    )
    op.create_table('lifecycle_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lifecycle_model_pkey'))
    )
    op.create_table('upsert_test_model',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='upsert_test'), nullable=False, comment='TypeID with prefix: upsert_test'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('upsert_test_model_pkey')),
    sa.UniqueConstraint('name', 'category', name='compound_constraint'),
    sa.UniqueConstraint('name', name=op.f('upsert_test_model_name_key')),
    comment='Test model for upsert operations'
    )
    op.create_index(op.f('upsert_test_model_category_idx'), 'upsert_test_model', ['category'], unique=False)
    op.create_table('after_find_model_with_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('another_example_id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=False),
    sa.ForeignKeyConstraint(['another_example_id'], ['another_example.id'], name=op.f('after_find_model_with_relationships_another_example_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('after_find_model_with_relationships_pkey'))
    )
    op.create_table('after_initialize_model_with_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('another_example_id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=False),
    sa.ForeignKeyConstraint(['another_example_id'], ['another_example.id'], name=op.f('after_initialize_model_with_relationships_another_example_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('after_initialize_model_with_relationships_pkey'))
    )
    op.create_table('example_related_model',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='related_model'), nullable=False, comment='TypeID with prefix: related_model'),
    sa.Column('example_record_id', activemodel.types.typeid.TypeIDType(prefix='test_record'), nullable=False),
    sa.ForeignKeyConstraint(['example_record_id'], ['example_record.id'], name=op.f('example_related_model_example_record_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('example_related_model_pkey')),
    comment='Test model with a foreign key relationship to ExampleRecord, used to test related model creation in factories.'
    )
    op.create_index(op.f('example_related_model_example_record_id_idx'), 'example_related_model', ['example_record_id'], unique=False)
    op.create_table('example_with_computed_property',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='example_computed'), nullable=False, comment='TypeID with prefix: example_computed'),
    sa.Column('another_example_id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=False),
    sa.ForeignKeyConstraint(['another_example_id'], ['another_example.id'], name=op.f('example_with_computed_property_another_example_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('example_with_computed_property_pkey'))
    )
    op.create_table('example_with_id',
    sa.Column('id', activemodel.types.typeid.TypeIDType(prefix='myid'), nullable=False, comment='TypeID with prefix: myid'),
    sa.Column('another_example_id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=True),
    sa.Column('example_record_id', activemodel.types.typeid.TypeIDType(prefix='test_record'), nullable=True),
    sa.ForeignKeyConstraint(['another_example_id'], ['another_example.id'], name=op.f('example_with_id_another_example_id_fkey')),
    sa.ForeignKeyConstraint(['example_record_id'], ['example_record.id'], name=op.f('example_with_id_example_record_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('example_with_id_pkey')),
    comment='example table with foreign keys'
    )
    op.create_table('lifecycle_model_with_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('another_example_id', activemodel.types.typeid.TypeIDType(prefix='myotherid'), nullable=False),
    sa.ForeignKeyConstraint(['another_example_id'], ['another_example.id'], name=op.f('lifecycle_model_with_relationships_another_example_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lifecycle_model_with_relationships_pkey')),
    comment='Model used to test after_save accessing a relationship.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifecycle_model_with_relationships')
    op.drop_table('example_with_id')
    op.drop_table('example_with_computed_property')
    op.drop_index(op.f('example_related_model_example_record_id_idx'), table_name='example_related_model')
    op.drop_table('example_related_model')
    op.drop_table('after_initialize_model_with_relationships')
    op.drop_table('after_find_model_with_relationships')
    op.drop_index(op.f('upsert_test_model_category_idx'), table_name='upsert_test_model')
    op.drop_table('upsert_test_model')
    op.drop_table('lifecycle_model')
    op.drop_table('example_without_comments')
    op.drop_table('example_with_simple_json')
    op.drop_table('example_with_jsonb')
    op.drop_table('example_with_comments')
    op.drop_index(op.f('example_record_another_with_index_idx'), table_name='example_record')
    op.drop_table('example_record')
    op.drop_table('delete_model')
    op.drop_table('delete_example_with_id')
    op.drop_table('another_example')
    op.drop_table('after_initialize_model')
    op.drop_table('after_find_model')
    # ### end Alembic commands ###
