# IMPORTANT: This file is auto-generated. Do not edit directly.

from typing import Protocol, TypeVar, Any, Generic
import sqlmodel as sm
from sqlalchemy.sql.base import _NoArg

T = TypeVar("T", bound=sm.SQLModel, covariant=True)


class SQLAlchemyQueryMethods(Protocol, Generic[T]):
    """Protocol defining SQLAlchemy query methods forwarded by QueryWrapper.__getattr__"""

    def add_columns(self, *entities: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def add_cte(
        self, *ctes: Any, nest_here: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def alias(
        self, name: Any = None, flat: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def argument_for(
        self, argument_name: Any, default: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def as_scalar(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def column(self, column: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def compare(self, other: Any, **kw: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def compile(
        self, bind: Any = None, dialect: Any = None, **kw: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def correlate(self, *fromclauses: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def correlate_except(self, *fromclauses: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def corresponding_column(
        self, column: Any, require_embedded: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def cte(
        self, name: Any = None, recursive: Any = False, nesting: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def distinct(self, *expr: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def except_(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def except_all(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def execution_options(self, **kw: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def exists(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def fetch(
        self,
        count: Any,
        with_ties: Any = False,
        percent: Any = False,
        **dialect_kw: Any,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def filter(self, *criteria: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def filter_by(self, **kwargs: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def from_statement(self, statement: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def get_children(self, **kw: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def get_execution_options(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def get_final_froms(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def get_label_style(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def group_by(
        self, _GenerativeSelect__first: Any = _NoArg.NO_ARG, *clauses: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def having(self, *having: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def intersect(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def intersect_all(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def is_derived_from(self, fromclause: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def join(
        self, target: Any, onclause: Any = None, isouter: Any = False, full: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def join_from(
        self,
        from_: Any,
        target: Any,
        onclause: Any = None,
        isouter: Any = False,
        full: Any = False,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def label(self, name: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def lateral(self, name: Any = None) -> "SQLAlchemyQueryMethods[T]": ...
    def limit(self, limit: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def memoized_instancemethod(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def offset(self, offset: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def options(self, *options: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def order_by(
        self, _GenerativeSelect__first: Any = _NoArg.NO_ARG, *clauses: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def outerjoin(
        self, target: Any, onclause: Any = None, full: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def outerjoin_from(
        self, from_: Any, target: Any, onclause: Any = None, full: Any = False
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def params(
        self, _ClauseElement__optionaldict: Any = None, **kwargs: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def prefix_with(
        self, *prefixes: Any, dialect: Any = "*"
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def reduce_columns(
        self, only_synonyms: Any = True
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def replace_selectable(
        self, old: Any, alias: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def scalar_subquery(
        self,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def select(self, *arg: Any, **kw: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def select_from(self, *froms: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def self_group(self, against: Any = None) -> "SQLAlchemyQueryMethods[T]": ...
    def set_label_style(self, style: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def slice(self, start: Any, stop: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def subquery(self, name: Any = None) -> "SQLAlchemyQueryMethods[T]": ...
    def suffix_with(
        self, *suffixes: Any, dialect: Any = "*"
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def union(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def union_all(self, *other: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def unique_params(
        self, _ClauseElement__optionaldict: Any = None, **kwargs: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def where(self, *whereclause: Any) -> "SQLAlchemyQueryMethods[T]": ...
    def with_for_update(
        self,
        nowait: Any = False,
        read: Any = False,
        of: Any = None,
        skip_locked: Any = False,
        key_share: Any = False,
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def with_hint(
        self, selectable: Any, text: Any, dialect_name: Any = "*"
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def with_only_columns(
        self, *entities: Any, maintain_column_froms: Any = False, **_Select__kw: Any
    ) -> "SQLAlchemyQueryMethods[T]": ...
    def with_statement_hint(
        self, text: Any, dialect_name: Any = "*"
    ) -> "SQLAlchemyQueryMethods[T]": ...
