"""Generate the QueryWrapper SQLAlchemy protocol modules."""

import inspect
import logging
import subprocess
from pathlib import Path
from string.templatelib import Template
from typing import Any

from sqlmodel.sql.expression import SelectOfScalar

logger = logging.getLogger(__name__)

REGENERATE_COMMAND = "uv run python -m activemodel.cli"
PROTOCOL_DIR = Path(__file__).resolve().parent.parent / "types"
RUNTIME_PROTOCOL_PATH = PROTOCOL_DIR / "sqlalchemy_protocol.py"
STUB_PROTOCOL_PATH = PROTOCOL_DIR / "sqlalchemy_protocol.pyi"


def _render_template(template: Template) -> str:
    rendered: list[str] = []

    for index, string_part in enumerate(template.strings):
        rendered.append(string_part)

        if index >= len(template.interpolations):
            continue

        rendered.append(str(template.interpolations[index].value))

    return "".join(rendered)


def _run_ruff(command: list[str], *, description: str) -> None:
    subprocess.run(command, check=True)
    logger.info("%s: %s", description, command[-1])


def _render_parameter(parameter: inspect.Parameter) -> str:
    if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
        return f"*{parameter.name}: Any"

    if parameter.kind is inspect.Parameter.VAR_KEYWORD:
        return f"**{parameter.name}: Any"

    if parameter.default is inspect.Parameter.empty:
        return f"{parameter.name}: Any"

    return f"{parameter.name}: Any = ..."


def _render_parameters(signature: inspect.Signature) -> str:
    rendered: list[str] = []
    inserted_keyword_separator = False

    for parameter in list(signature.parameters.values())[1:]:
        if parameter.kind is inspect.Parameter.KEYWORD_ONLY:
            if not inserted_keyword_separator:
                rendered.append("*")
                inserted_keyword_separator = True

            rendered.append(_render_parameter(parameter))
            continue

        if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
            inserted_keyword_separator = True

        rendered.append(_render_parameter(parameter))

    if not rendered:
        return ""

    return ", " + ", ".join(rendered)


def _render_stub_method(name: str, method: Any) -> str:
    try:
        signature = inspect.signature(method)
    except ValueError | TypeError:
        return _render_template(
            t"def {name}(self, *args: Any, **kwargs: Any) -> QueryWrapper[T]: ..."
        )

    parameters = _render_parameters(signature)
    return _render_template(t"def {name}(self{parameters}) -> QueryWrapper[T]: ...")


def _iter_select_methods() -> list[tuple[str, Any]]:
    methods: list[tuple[str, Any]] = []

    for name, method in inspect.getmembers(SelectOfScalar):
        if name.startswith("_"):
            continue

        if not inspect.isfunction(method) and not inspect.ismethod(method):
            continue

        methods.append((name, method))

    return methods


def _join_lines(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


def _render_runtime_module() -> str:
    return _join_lines(
        [
            '"""',
            "Auto-generated runtime companion for `sqlalchemy_protocol.pyi`.",
            "",
            "This module stays intentionally minimal so `activemodel.query_wrapper` can",
            "import `SQLAlchemyQueryMethods` at runtime without importing `QueryWrapper`.",
            "Type checkers should read `sqlalchemy_protocol.pyi` for the generated method",
            "signatures forwarded through `QueryWrapper.__getattr__`.",
            "",
            _render_template(
                t"Do not edit this file directly. Run `{REGENERATE_COMMAND}` to regenerate both"
            ),
            "files.",
            '"""',
            "",
            "from typing import Protocol",
            "",
            "import sqlmodel as sm",
            "",
            "",
            "class SQLAlchemyQueryMethods[T: sm.SQLModel](Protocol):",
            '    """Runtime protocol placeholder for QueryWrapper\'s forwarded methods."""',
            "",
            "    pass",
        ]
    )


def _render_stub_module() -> str:
    methods = _iter_select_methods()
    method_lines = [_render_stub_method(name, method) for name, method in methods]
    rendered_methods = [f"    {line}" for line in method_lines] or ["    pass"]

    return _join_lines(
        [
            '"""',
            "Auto-generated type stub for QueryWrapper's forwarded SQLAlchemy methods.",
            "",
            "`sqlalchemy_protocol.py` is the runtime module imported by the package.",
            "This stub carries the generated method signatures used by type checkers for",
            "methods forwarded through `QueryWrapper.__getattr__`.",
            "",
            _render_template(
                t"Do not edit this file directly. Run `{REGENERATE_COMMAND}` to regenerate both"
            ),
            "files.",
            '"""',
            "",
            "from typing import Any, Protocol",
            "",
            "import sqlmodel as sm",
            "",
            "from ..query_wrapper import QueryWrapper",
            "",
            "",
            "class SQLAlchemyQueryMethods[T: sm.SQLModel](Protocol):",
            '    """Type-checker protocol for SQLAlchemy methods forwarded by QueryWrapper."""',
            "",
            *rendered_methods,
        ]
    )


def _write_protocol_module(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    _run_ruff(["ruff", "check", str(path), "--fix"], description="ruff check")
    _run_ruff(["ruff", "format", str(path)], description="ruff format")


def generate_sqlalchemy_protocol() -> None:
    """Generate the runtime module and stub for QueryWrapper SQLAlchemy methods."""
    logger.info("generating sqlalchemy protocol files")

    PROTOCOL_DIR.mkdir(parents=True, exist_ok=True)

    _write_protocol_module(RUNTIME_PROTOCOL_PATH, _render_runtime_module())
    _write_protocol_module(STUB_PROTOCOL_PATH, _render_stub_module())


if __name__ == "__main__":
    generate_sqlalchemy_protocol()
