name: Build and Publish to PyPI
on:
  push:
    branches:
      - main
      - master

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

env:
  # avoid build failures due to flaky pypi
  PIP_DEFAULT_TIMEOUT: 60
  PIP_RETRIES: 5

  DATABASE_HOST: localhost

jobs:
  # release-please:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   outputs:
  #     release_created: ${{ steps.release.outputs.release_created }}
  #   steps:
  #     - uses: googleapis/release-please-action@main
  #       id: release
  #       with:
  #         release-type: python
  #         # token: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: docker compose up -d --wait
      - run: uv sync

      # `uv run` prefix is required since the venv is not activated

      - name: Make sure we can import the module
        run: uv run python -c 'import ${{ github.event.repository.name }}'
        
      - run: uv run pytest

      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@v6
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     version-file: "./pyproject.toml"
      #     version-path: "project.version"
      #     fallback-version: "1.0.0"
      #     output-file: "CHANGELOG.md"

      # # NOTE must run after versioning otherwise the right version won't be pushed
      # - name: Build distribution package
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   run: uv build

      # - name: Publish to PyPI
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   # `gh secret set PYPI_API_TOKEN --app actions --body $PYPI_API_TOKEN`
      #   run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      # - name: Github Release
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
      #     tag_name: ${{ steps.changelog.outputs.tag }}
